### PR TITLE
Enable Authentication and Access Control Via OAuth and Team Membership

### PR DESCRIPTION
**Pull request by ericpassmore**
Added logic to authenticate against GitHub, and then check membership in engineering team for access control. 
- env file for OAuth secretes
- documentation on authentication and how to setup env file
- new stateless GitHubOauth class to handle OAuth actions 
- new EnvStore class to manage env file 
- UI updates with github username and avatar presented at login
- new application endpoints for logout and OAuth support 
- new tests for new webservice endpoints 
- documentation updates for webservice updates

### CODE REVIEW

**Comment by ericpassmore** [comment]
fixes #89 
fixes #44

**Review by kj4ezj — COMMENTED** [review]
This is not my formal review, I just found a typo and figured I'd provide a heads-up right away instead of waiting till the end.

**Comment by kj4ezj** [comment]
> Added logic to authenticate against GitHub, and then check membership in engineering team for access control.

Can we expand this from [enf-engineering](https://github.com/orgs/eosnetworkfoundation/teams/enf-engineering) to [enf-employees](https://github.com/orgs/eosnetworkfoundation/teams/enf-employees)? The performance benchmark data typically has broader interest within the organization, beyond just the engineering team.

**Comment by ericpassmore** [comment]
> > Added logic to authenticate against GitHub, and then check membership in engineering team for access control.
> 
> Can we expand this from [enf-engineering](https://github.com/orgs/eosnetworkfoundation/teams/enf-engineering) to [enf-employees](https://github.com/orgs/eosnetworkfoundation/teams/enf-employees)? The performance benchmark data typically has broader interest within the organization, beyond just the engineering team.

Short answer is not at this time, because not all enf employees are on github, and we do not have a team that includes all employees. To fix this we could to add google as another oauth provider, and I can open an issue to track that. 

In addition, I will add the team membership to the env configuration file. This will make it easier to change the team that controls access.

**Comment by ericpassmore** [comment]
Added HTTP API using `Authorization` header. Fixes #36

**Review by kj4ezj — APPROVED** [review]

**Pull request merged**
